# Generated by Django 3.2.10 on 2021-12-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='path',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(default=1, upload_to='qrcodes'),
            preserve_default=False,
        ),
    ]
