# Generated by Django 3.2.10 on 2022-01-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211231_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='image',
            field=models.ImageField(null=True, upload_to='qrcodes'),
        ),
    ]
